language: ruby
env: RAILS_ENV=test
rvm:
  - "2.0.0"
before_script:
  - bundle exec rake db:create --trace
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exex rspec
